name: Debug & Release

on:
  # Triggers the workflow on every pull request to master branch
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*.*.*
    paths:
      - 'Android/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Android/MSTG-Android-Kotlin-App

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: ./Android/MSTG-Android-Kotlin-App/app/build/outputs/apk/debug/app-debug.apk

  release:
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/')
    defaults:
      run:
        working-directory: Android/MSTG-Android-Kotlin-App

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build release APK
        run: ./gradlew assembleRelease

      - uses: ilharp/sign-android-release@v1  
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDir: ./app/build/outputs/apk/release
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Rename signed APK 
        run: mv ./app/build/outputs/apk/release/app-release-unsigned-signed.apk ./app/build/outputs/apk/release/MASTG-Android.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          draft: true
          generate_release_notes: true
          files: |
            ./app/build/outputs/apk/release/MASTG-Android.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Rename build 
        run: mv ./app/build/outputs/apk/release/app-release-unsigned.apk ./app/build/outputs/apk/release/MASTG-Android.apk

      - name: Upload debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: ./Android/MSTG-Android-Kotlin-App/app/build/outputs/apk/debug/app-debug.apk
